export const tempResult = {
  status: "OK",
  request_id: "80866fef-f3df-41d7-8bb4-64133c87f024",
  parameters: {
    query: "data scientist",
    page: 1,
    num_pages: 10,
  },
  data: [
    {
      employer_name: "Offerista Group GmbH",
      employer_logo:
        "https://www.offerista.com/wp-content/uploads/2021/05/Logo.svg",
      employer_website: "http://www.offerista.com/en",
      employer_company_type: null,
      job_publisher: "Learn4Good",
      job_id: "p3aXfSxAlxYAAAAAAAAAAA==",
      job_employment_type: "PERDIEM",
      job_title: "Fullstack Web Developer",
      job_apply_link:
        "https://www.learn4good.com/jobs/berlin/germany/software_development/2477930276/e/",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.3993,
      job_description:
        "WE ARE LOOKING FOR...\n\n… а Fullstack Web Developer (f/m/d) for our office in Sofia, Berlin or Dresden. Your passion is web development? Then you should join our awesome location functional Web Development team.\n\nYou will work for a modern website, millions of people use and bring our platform to the next level. In your joint planning meetings with the teams Product, Sales and Marketing you keep yourself up to date. Moreover, you chose your own working technique in order to work based on your personal needs!\n\nYOUR MISSION WITH US\n• You share responsibility for the creative design of our variety of websites\n• You create SPA, dynamic widgets, and work on our portals\n• You shape our web, processes, and tools in collaboration with designers and other developers\n• You develop and maintain reusable and solid responsive frontend components\n• You develop Restful endpoints and improve our current Symfony stack\n• You create technical specifications and documentation\n• As an experienced engineer you will help your colleagues with your vast experience by consulting and coaching\n\nTHIS IS WHAT YOU BRING ALONG\n• You provide proficient development experience (at least 3-5 years)\n• Experience in TDD, JavaScript (ES6+) and good software engineering practices\n• Throughout your career, you have gained very good knowledge of modern libraries like:\nVue, Next.js, React\n• Experience in PHP, Symfony, Docker\n• It will be some extra points if you are experienced in: SASS, CSS, HTML5\n• You have experience with AWS, CI/CD processes and Git\n• You are solution-oriented and provide a high sense of responsibility and quality\n• Being flexible, taking the initiative and thinking independently are your trademarks\n• Curiosity about technical innovation, hands-on, creativity and teamwork skills\n• You are very good in English\n\nDRESDEN | BERLIN | ESSEN | VIENNA | SOFIA\n\nBECOME PART OF OUR TEAM AND SHAPE WITH US.\n\nWe are visionaries, betterers and thinkers. With dedication we design the digital shopping world of tomorrow. Already known as the market leader in digital retail marketing in the DACH area, our state-of-the-art products provide international digital coverage and store visits to retailers. The achievements fill us with pride, the future spurs us on. We are Offerista - and we are looking for bright minds that will make us even better.\n\nP.S. Don't be afraid to share this with your friends or co-workers - We are a growing business with many opportunities.\n• #diversity&inclusion - be YOURSELF and get involved in our #nondiscrimination corporate culture with flat hierarchies, openness and a lot of genuinely nice and decent people\n• #lean - lean, agile and highly dynamic working environment with various activities and plenty of room for creativity and co-designing our common path\n• #personal growth - we support you to develop your own personal Offerista Development Plan, workshops, trainings and regular feedback\n• #office goals - work in modern, playful and centrally located offices, ergonomically equipped and with daily fresh fruits, vegetables & yogurt as well as a tea and coffee flatrate with your favorite milk (vegan-friendly)\n• #stateoftheart - laptop, keyboard, screen? Here you get the latest technical equipment\n• #100% flexible - flexible working time models, trust-based working time, mobile working arrangements as well as the possibility of a sabbatical\n• #teamfuckingawesome - experience legendary team events and celebrations with us, such as our annual summer party or our Christmas event (Covid friendly)\n• #family first - bring your child and dog to the office and let us support you with an allowance for your childcare\n• #corporate benefits - receive exclusive discounts with various providers\n• #sustainability - we are climate neutral! But there's still more to do! Get involved as an #orange officer to make Offerista even more sustainable",
      job_is_remote: false,
      job_posted_at_timestamp: 1690416000,
      job_posted_at_datetime_utc: "2023-07-27T00:00:00.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=p3aXfSxAlxYAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-01-26T00:00:00.000Z",
      job_offer_expiration_timestamp: 1706227200,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113300",
      job_onet_job_zone: "4",
      job_occupational_categories: ["Javascript", "Full Stack Developer"],
    },
    {
      employer_name: "Clark Germany GmbH",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6AqmEBDbUBuViRsjU7PPGAlfuTkColjqvUiqw&s=0",
      employer_website: "http://www.clark.de",
      employer_company_type: null,
      job_publisher: "HRos.io",
      job_id: "FizdS80_qeMAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Web Developer (m/f/x)",
      job_apply_link: "https://jobs.hros.io/job/web-developer-mfx-19181",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5269,
      job_description:
        "CLARK Group is one of the world's leading insurtechs. As the first unicorn company from Frankfurt, we are on the mission to become Europe's best insurance advisor. We develop technological solutions and mobile apps that enable our customers to manage, compare and optimize their insurance policies online in the most convenient way. The digital user experience is complemented by personal advice from trained experts. In total, CLARK Group includes around 30 brands offering the best possible insurance experience to more than 2 million customers in six European markets.\n\nThe advantages of our innovative technology and our customer-focused culture unite us as one group. We are supported by investors such as Allianz X, Portage, White Star Capital, Yabeo and Tencent. Every day, over 700 employees from more than 40 nations in Germany, Austria, Switzerland, the UK, France and the Netherlands shape the digital insurance world of tomorrow. Become a part of this international team and join us on our path to success.\n\nYour responsibilities\n\nOur web platform clark.de is the first touch point with our brand and applications for many users. You’ll work with stakeholders from marketing, product development and sales to guarantee a great user experience. Our WordPress-based system provides critical user journeys that span from landing-, SEO- to purely informational pages. As part of your role you will:\n• Developing full-stack solutions utilizing WordPress for multiple web properties.\n• Facilitating marketing programs by implementing customizations to landing pages, CMS, and marketing automation tools.\n• Demonstrating a strong understanding and skills in technical SEO to ensure website discoverability and reach for the target audience.\n• Providing an engineering perspective on user flow, architecture, and implementation to aid in project scoping and identifying efficient solutions to meet goals.\n• Collaborating with marketing stakeholders to identify areas for improvement in conversion rate optimization across web properties.\n• Supporting day-to-day website updates, bug fixes, and general maintenance tasks while prioritizing accordingly.\n• Building an agile Martech stack in partnership with the marketing team.\n• Implementing web analytics and tracking tools.\n\nYour profile\n• As an experienced web developer with a minimum of 3 years of working experience, you have a deep understanding of user experience and have gained knowledge working in marketing technology.\n• You have a track record of supporting marketing teams in the creation and maintenance of campaigns, newsletters, landing pages, and analytics and have the ability to intuitively support similar projects.\n• Your passion for staying current with emerging technologies is balanced with the ability to recognize when tried-and-true solutions are the best approach for creating reliable and effective user experiences.\n• You are already based in Germany or willing to relocate to Germany from within the European Union.\n• You possess fluency in both English and German.\n\nRequirements\n• Strong skills in maintaining and developing WordPress v6 stacks\n• Solid knowledge and working experience with PHP and JavaScript, HTML, and CSS and package managers for PHP (Composer) and JS (NPM/Yarn)\n• Strong knowledge about CDNs and caching layers\n• Good knowledge of Git\n• Good understanding of CI/CD Tools like Github Actions, CircleCI, Jenkins\n• Experience with end-to-end testing frameworks such as Cypress\n• Strong understanding of technical SEO\n• Independence, self-motivation, and organization\n• Critical and solution-oriented thinking\n• Excellent communication skills in the technical and non-technical environment\n\nWhy CLARK?\n• You are part of a leading global insurtech and change the insurance industry together with us\n• Hybrid working models and flexible working hours\n• 30 days holiday & 2 days impact days\n• Extensive range of exclusive discounts for employees\n• Education and personal development\n• Support for personal volunteering activities\n• Free drinks, fresh fruit and tasty snacks\n• Cultural initiatives and team events\n\nAt CLARK we embrace diversity.\n\nWe are creating the ideal work environment for dedicated and talented people, no matter their ethnicity, identity, religion and age - we aim at giving everybody the same chances and opportunities.\n\nSounds exciting? You have no idea! We’re looking forward to reading your application.",
      job_is_remote: true,
      job_posted_at_timestamp: 1682641081,
      job_posted_at_datetime_utc: "2023-04-28T00:18:01.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=FizdS80_qeMAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-08-26T00:18:01.000Z",
      job_offer_expiration_timestamp: 1693009081,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
    },
    {
      employer_name: "Bloom Partners GmbH",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSheEljMMQcILgVfmioDyU-vbQU9VNGNf5c9OD&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "GermanTechJobs",
      job_id: "XQYKqB7XXbUAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title:
        "Lead Engineer E-Commerce & Web Development  (m/f/d ) JavaScript   ",
      job_apply_link:
        "https://germantechjobs.de/en/jobs/Bloom-Partners-GmbH-Lead-Engineer-E-Commerce--Web-Development--mfd",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.7032,
      job_description:
        "Lead Engineer E-Commerce & Web Development (m/f/d )    Salary: 70000 - 90000 EUR per year\n\nAt Bloom Partners GmbH we are looking for a JavaScript engineer!\n\n  ️ Our tech stack:\nAWS, Angular, Business Intelligence, CAN, Cloud, CMS, CRM, Docker, ElasticSearch, Flutter, Java, JavaScript, Kubernetes, Marketing, Mobile, MySQL, REST, Shopify, Web, WordPress, Xamarin, microservices\n\n   Rquirements:\nWHAT YOU BRING WITH YOU\n\n- Master or bachelor's degree preferably in Computer Science\n- Over 3 years of Full Stack software engineering experience developing, prototyping and designing integrated consumer facing web applications\n- Deep, hands-on expertise setting up and configuring advanced E-Commerce solutions with Shopify, WooCommerce and WordPress (other CMS tools are a plus)\n- You are passionate about building and leading tech teams that focus on impact, technical excellence, and quality.\n- Ability to make decisions to advance each project. You are comfortable owning and solving even the most ambitious technical challenges and defining a path forward.\n- You are creative in framing solutions and data driven and analytical in your decision making.\n- Passion for building data-centric and smart digital user experiences\n- Excellent communication skills. Within the team and across the organization you can communicate transparently and effectively.\n- Excellent English language skills at a native level, German is a plus.\n- You’re willing to relocate to Berlin.\n\n  ‍    ‍   Your responsibilities are:\nTHE ROLE\nAt Bloom Partners we improve the daily lives of some of the most trusted brands in the world through designed digital-oriented strategies and organizations!\n\nJoin our Bloom Technology team in Berlin and help us shape the daily lives of some of the most trusted brands in the world! At Bloom you will have the opportunity to leave your footprint and create a direct impact on our customers, our product, our company, and our engineering practices.\n\nAs a Lead Engineer E-Commerce & Web Development (m/f/d) with extensive Full Stack experience and experience with Shopify, WooCommerce and WordPress, you will be playing a key role within the Engineering team at Bloom.\n\nYou know how to address each challenge - coding hands-on to prototype a solution, holding technical presentations or conducting brainstorming sessions with engineers from other tribes to tackle a certain problem - You know it best!!\n\nWe are looking for an ambitious, self-motivated Full-stack engineer / Software ‘Generalist’ (m/f/d) with extensive Web Development, E-Commerce & Cloud-based tools expertise, who wants to take an active and key role in growing our Test & Learn Technology Practice.\n\nYour main tasks and responsibilities with which you will have fun:\n\n- Set up and configure high-quality E-Commerce and online landing pages using tools like Shopify, WooCommerce and Wordpress (or other CMS).\n- Select, set up and configure best-in-class tracking and monitoring tools to optimize customer journeys and conversions.\n- Assist in the design of engaging user experiences with a clear focus on digital storytelling and conversion.\n- Actively assist the project teams in capturing comprehensive data streams to validate / dismiss key hypotheses.\n- Design and develop re-usable data integrations with leading CRM, marketing automation and dashboarding/reporting tools.\n- Work, interact and establish agile delivery processes with a cross-functional team of Product Owners, Developers, Consultants and other stakeholders.\n- Take the lead assembling and up-skilling a cross-functional engineering team for rapid delivery of integrated web applications and other digital assets.\n\nOUR TECH STACK\n\nOur Tech stack includes:\n\n- Angular, ReactJS and other modern JavaScript Frameworks\n- Cross-platform mobile development platforms based on Xamarin and Flutter\n- REST-based APIs and advanced architecture patterns\n- Java-based Microservices\n- Scalable database infrastructures using Elasticsearch and MySQL\n- Business Intelligence and various data analytics tools\n- Industry Leading Cloud Operations based on AWS, Kubernetes, Docker\n\nView this job and over 500 other transparent jobs with salaries (      ) & tech stacks (  ️) on GermanTechJobs\n\nCategory: JavaScript Developer / Engineer\nLocation address: Paul-Lincke-Ufer 39-40, Berlin, Germany\n\nSalary: 70000 - 90000 EUR per year\n\nBenefits & perks that we offer:\n40-hour work week, Career paths and annual reviews, Coffee, tea, Company workshops and knowledge sharing, Cool office, Individual educational training budget, International team, Relax / Chillout room, Startup culture, Snacks & drinks, Team social events, Well connected office\n\nBloom Partners GmbH - More about us and the role:\nWHY BLOOM PARTNERS ?\nBecause we will provide you with:\n\n- Collaboration with a diverse, international and outstanding team. We only hire the best. Our quality standards are high, and our employees enjoy working alongside other high achievers;\n- A spacious, modern and inspiring working environment in the center of Berlin-Kreuzberg\n- Flexibility in terms of working hours and home office work;\n- A wider range of responsibilities in a humorous and positive team environment;\n- Free coffee, snacks, fresh fruit and beverages to help yourself anytime and start your day the best way possible;\n- The chance to shape our product, see quick results and contribute to its growth and the fast growth of Bloom Partners; \n- A well-rounded experience: We offer a diverse and dynamic environment where you will get the chance to work directly with executives and gain a broad knowledge base across multiple areas of the business;\n- Competitive salary compensation that helps you enjoy your life in Berlin;\n\nAnd much more...\nAre you up for this new challenge? Then don't think it more and apply!\nEkaterina is looking forward to your application in English!\n\nABOUT US\nBloom Partners is a digital growth firm.\nAs consultants, technologists and entrepreneurs, we are champions of digital transformation. We enable our clients to grow sustainably, as a business, as a workplace and as a provider of exceptional ideas, products and services. For us, digital transformation is first and foremost about improving the daily lives of consumers and supporting companies that share this belief.\n\nBloom Partners unlocks digital growth opportunities.\nAnd we are proud to do so for some of the most trusted brands in the world. We design strategies and organizations for digital transformation that provide speed, clarity, and growth. We pioneer and test ideas that excite consumers and go beyond boundaries. We develop, grow, and run digital businesses and platforms that make a difference in the market.\n\nA group of builders, thinkers, and entrepreneurs.\nWe are digital enthusiasts, combining profound experiences in business strategy, marketing, entrepreneurship, technological innovation, and design. Respect and affection for consumers and our client’s brands are the foundations of our work. Our team is embedded in a trusted network of start-ups, technology experts, venture capitalists and think tanks.\n\nAre you looking for JavaScript jobs in Berlin?",
      job_is_remote: false,
      job_posted_at_timestamp: 1690370711,
      job_posted_at_datetime_utc: "2023-07-26T11:25:11.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=XQYKqB7XXbUAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-09-24T08:47:56.000Z",
      job_offer_expiration_timestamp: 1695545276,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: [
        "WHAT YOU BRING WITH YOU<br><br>- Master or bachelor's degree preferably in Computer Science<br>- Over 3 years of Full Stack software engineering experience developing",
        "prototyping and designing integrated consumer facing web applications<br>- Deep",
        "hands-on expertise setting up and configuring advanced E-Commerce solutions with Shopify",
        "WooCommerce and WordPress (other CMS tools are a plus)<br>- You are passionate about building and leading tech teams that focus on impact",
        "technical excellence",
        "and quality.<br>- Ability to make decisions to advance each project. You are comfortable owning and solving even the most ambitious technical challenges and defining a path forward.<br>- You are creative in framing solutions and data driven and analytical in your decision making.<br>- Passion for building data-centric and smart digital user experiences<br>- Excellent communication skills. Within the team and across the organization you can communicate transparently and effectively.<br>- Excellent English language skills at a native level",
        "German is a plus.<br>- You’re willing to relocate to Berlin.",
      ],
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: 70000,
      job_max_salary: 90000,
      job_salary_currency: "EUR",
      job_salary_period: "YEAR",
      job_highlights: {},
      job_job_title: "Lead engineer",
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: ["15-1254.00 Web Developers"],
    },
    {
      employer_name: "Henkel",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: "Henkel",
      job_id: "J675XIxMOx8AAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Senior Web Frontend Developer (d/f/m)",
      job_apply_link:
        "https://www.henkel.com/careers/jobs-and-application/1808906-1808906",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.9286,
      job_description:
        "At Henkel, you can be a game changer and craft your career. Unleash your entrepreneurial spirit by bringing your ideas to life within a global team. Our leading brands and technologies, along with our high-performing businesses will provide you with countless opportunities to develop your skills and explore new paths. Your career at Henkel will contribute to a more sustainable future, while you grow within our vibrant, diverse culture of trust and belonging. If you're up for challenging the status quo, join our team of pioneers and make your mark on the future with us.\n\nDo you dare to make an impact?\nYOUR ROLE\n• Write high quality code by following Angular/Typescript best practices and the company internal guidelines\n• Support the team by doing code reviews and providing new features to the project\n• Attend technical meetings to align with other technical teams\n• Be available for your colleagues when your support is needed\n• Provide user interfaces that comply with the designs and wireframes\n• Fix bugs as efficiently as possible\n• Have an interest in complex architectures and their understanding",
      job_is_remote: false,
      job_posted_at_timestamp: 1678665600,
      job_posted_at_datetime_utc: "2023-03-13T00:00:00.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=J675XIxMOx8AAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: false,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: "Senior",
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
    },
    {
      employer_name: "trinckle",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: "AMjobCenter",
      job_id: "X1EiFBRP594AAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Senior Frontend Web Developer (f/d/m)",
      job_apply_link:
        "https://www.amjobcenter.com/job/berlin-2-senior-frontend-web-developer-f-d-m/",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6084,
      job_description:
        "The Role\n\nWe’re looking for a Senior Frontend Web Developer (f/d/m) with 7+ years of experience to join our team of 7 developers in Berlin and help us revolutionize digital manufacturing.\n\nAs a Senior Frontend Web Developer, you’ll play a critical role in building our web frontend products and contributing to our frontend libraries. You’ll work with our cross-functional teams to create innovative, responsive web applications with a focus on user experience and accessibility. At trinckle we believe in the quality of our teams and respect all styles. The Senior Frontend Web Developer meets once a week (in Berlin) and we allow Hybrid flexibility to do coding, Frontend web work, etc., our workforce is equipped.\n\nYour profile\n• 5+ years of frontend focus\n• Up-to-date expertise of HTML, CSS, JavaScript\n• Extensive experience in building responsive web application frontends\n• Proven ability to develop JS libraries with robust architecture\n• Knowledge of Vanilla JavaScript and familiarity with modern JS frameworks (React is a plus)\n• Familiarity with Git and Jira\n• Located in Germany or the EU is preferred (plans to move to Berlin, please advise in cover letter)\n\nWe Value:\n• Independent and collaborative work style\n• Strong technical leadership skills with a focus on decision-making\n• A talent for mentoring junior developers\n• Strong technical and spatial imagination\n• Passion for your work and continuous learning\n• Clear and well-structured code\n• Ability to work with business customers\n\nWhy trinckle?\n• Competitive compensation\n• Central loft office located in the heart of vibrant Berlin-Kreuzberg\n• A diverse, equitable, inclusive, and belonging workplace\n• Regular company events (video game nights, kayaking, etc.) and international team cooking\n• Opportunity to learn about cool technologies (3D printing, WebGL, algorithm-driven design, cloud computing, etc.)\n• Choose the way you work, use your favorite tools\n• Friendly, international, and motivated work culture of coworkers\n\nAbout us\n\nHello, we are trinckle, an ambitious and award-winning tech Start-Up in Berlin, backed by top VCs. 3D-printing is our specialty and our cloud-based software, paramate, automates 3D design and enables mass customization of 3D-printed products. Our high-performance, easy to implement cloud-based solution is a tool for making innovative customizing applications. It is used for a wide range of industries, from mechanically optimized robotic components to patient-specific orthotics. And along with the 3D printing world, our team is growing and developing as well.\n\nTagged as: frontend web html css javascript git jira berlin digital manufacturing additive manufacturing 3d",
      job_is_remote: false,
      job_posted_at_timestamp: 1680522959,
      job_posted_at_datetime_utc: "2023-04-03T11:55:59.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=X1EiFBRP594AAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-08-01T23:59:59.000Z",
      job_offer_expiration_timestamp: 1690934399,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 84,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: "Senior",
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
    },
    {
      employer_name: "Mobiteam",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: "Digital Agency Network",
      job_id: "VoEmkCyQnnYAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "WordPress Developer",
      job_apply_link:
        "https://digitalagencynetwork.com/job/wordpress-developer-mobiteam/",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6412,
      job_description:
        "Mobiteam is looking for a WordPress Developer (CSS+WP) to join their team in Berlin.",
      job_is_remote: false,
      job_posted_at_timestamp: 1679443200,
      job_posted_at_datetime_utc: "2023-03-22T00:00:00.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=VoEmkCyQnnYAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: false,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
    },
    {
      employer_name: "Honeypot GmbH",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc_wTZhnHl_-aHXKt9wSXXQ41Ku2EIQQJ2kf5l&s=0",
      employer_website: "http://www.honeypot.io",
      employer_company_type: null,
      job_publisher: "GermanTechJobs",
      job_id: "rXKqUpqiHcoAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Frontend Developer JavaScript   ",
      job_apply_link:
        "https://germantechjobs.de/jobs/Honeypot-GmbH-Frontend-Developer",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.7205,
      job_description:
        "Frontend Developer\n\nHoneypot GmbH sucht JavaScript Spezialisten! Gehaltspanne 60000 - 90000 EUR pro Jahr\n\n  ️ Verwendete Technologien:\nAngular, React, React Native, Vue, Frontend, JavaScript, CSS, Polymer, Gulp, AJAX, Backbone, Ember, TypeScript\n\n   Anforderungen und Ihr Profil:\nHoneypot - Signup and get your dream job on Europe's top Developer-Focused job platform!\n\nHoneypot supports Software Developers, DevOps Engineers and Engineering Leaders as well as Data Scientists, Data Engineers and Machine Learning Engineers.\n\nCompanies can search for developers based on skills and specialisations — the qualifications and requirements of each company may differ depending on their tech needs.\n\nCurrently, there is an increasingly high demand for Backend and Frontend Developer roles for companies hiring on Honeypot.\n\n  ‍    ‍   Ihre Verantwortlichkeiten:\nHoneypot supports Software Developers, DevOps Engineers and Engineering Leaders as well as Data Scientists, Data Engineers and Machine Learning Engineers.\n\nCompanies can search for developers based on skills and specialisations — the qualifications and requirements of each company may differ depending on their tech needs.\n\nCurrently, there is an increasingly high demand for Backend and Frontend Developer roles for companies hiring on Honeypot.\n\nSehen Sie diesen Job und über 500 andere transparente Jobs mit Gehältern (      ) & Technologien (  ️) auf GermanTechJobs\n\nKategorie: JavaScript\nAdresse: Schlesische Straße 26, Berlin, Germany\n\nGehalt: 60000 - 90000 EUR pro Jahr\n\nWas wir bieten:\n\nHoneypot GmbH - Über uns:\nOn Honeypot, companies apply to you with salaries between €65k–€120k for Frontend software developers and tech stack upfront.\n\nHoneypot is a reverse-recruiting platform, meaning companies apply to you not the other way around. Your profile will indicate your ideal location, salary and tech stack so companies can send tailored interview invitations. Top developers on the platform usually receive multiple interview invitations meaning they can compare offers side-by-side for a better job search experience.\n\nCreating a profile is quick and easy, it takes less than five minutes to share your skills, experience and work preferences. And after that, your profile will be available to hundreds of companies located in Germany, the Netherlands, Switzerland and Austria.\n\nYou’ll also have access to dedicated career advisors who can offer personalised profile and interview support so you can focus on choosing a great job.\n\nSuchen Sie JavaScript Jobs in Berlin?",
      job_is_remote: false,
      job_posted_at_timestamp: 1690291511,
      job_posted_at_datetime_utc: "2023-07-25T13:25:11.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=rXKqUpqiHcoAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-14T07:03:34.000Z",
      job_offer_expiration_timestamp: 1702537414,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: [
        "Honeypot - Signup and get your dream job on Europe's top Developer-Focused job platform!<br><br>Honeypot supports Software Developers",
        "DevOps Engineers and Engineering Leaders as well as Data Scientists",
        "Data Engineers and Machine Learning Engineers. <br><br>Companies can search for developers based on skills and specialisations — the qualifications and requirements of each company may differ depending on their tech needs. <br><br>Currently",
        "there is an increasingly high demand for Backend and Frontend Developer roles for companies hiring on Honeypot. <br>",
      ],
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: 60000,
      job_max_salary: 90000,
      job_salary_currency: "EUR",
      job_salary_period: "YEAR",
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_occupational_categories: ["15-1252.00 Software Developers"],
    },
    {
      employer_name: "Tiens",
      employer_logo:
        "https://upload.wikimedia.org/wikipedia/en/1/1d/Tiens-logo.png",
      employer_website: "http://www.tiens.com/tiens/group/en/index.htm",
      employer_company_type: "Manufacturing",
      job_publisher: "Learn4Good.com",
      job_id: "BG6qfzphKhEAAAAAAAAAAA==",
      job_employment_type: "PARTTIME",
      job_title: "Web Developer - Bitrix",
      job_apply_link:
        "https://www.learn4good.com/jobs/berlin/germany/info_technology/2476401271/e/",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.3875,
      job_description:
        "Position: Web Developer - Bitrix (m/w/d)\n\nThe TIENS Group Co., Ltd. is a multinational conglomerate, that integrates industrial capital, business capital and financial capital with its scope of business covering biotechnology, health management, the hotel and tourism industry, education & training, e-commerce and finance investment, etc. With its business reaching over 190 countries, TIENS Group has set up branches in 110 countries & regions and has established strategic alliances with top-ranked enterprises from many countries.\n\nTIENS Europe Region is currently active in more than 20 markets.\n\nTasks\n• Meeting with the product and development teams to discuss ideas and plan the work\n• Writing and managing the application code primarily using PHP, but also JavaScript (VUE JS), Git, HTML, CSS and Bitrix\n• Develop and support existing integrations with various internal and external systems, microservices and messaging routers\n• Writing tests covering the major functionality of the application\n• Developing and implementing back-end architecture to introduce best practices concepts\n• Monitoring and improving back-end performance\n• Documenting application changes and describing functional parts of the applications\n• Supporting the wider technology team on key issues and overall product development\n• Provide ongoing support and training to staff, answering questions and troubleshooting any issues related to the Bitrix\n24 CRM system\n• Maintain all current sites from the Euro Asia Region\n\nRequirements\n• Bachelor’s degree in computer science, or a related field\n• 3+ years’ experience working as a PHP Developer\n• In-depth knowledge of PHP, JavaScript (VUE JS), Git, HTML, CSS and Bitrix 24 CRM\n• Ideally experience of AWS infrastructure, but if not then a very rapid learner\n• Knowledge of performance testing frameworks\n• Experience with browser-based debugging and performance testing software\n• Excellent troubleshooting and task management skills\n• Excellent speaking and writing in local and English languages\n\nBenefits\n• Flexible working hours\n• Employee discount on corporate products\n• Daily use of foreign languages\n• Warm and international culture based on respect, collaboration and giving your ideas a spotlight!\n• Interactive activities: team-building, company parties and events\n\nWe look forward to receiving your application in English with a current photo and stating your salary requirements and earliest possible starting date, thanks.",
      job_is_remote: false,
      job_posted_at_timestamp: 1690329600,
      job_posted_at_datetime_utc: "2023-07-26T00:00:00.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=BG6qfzphKhEAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-01-25T00:00:00.000Z",
      job_offer_expiration_timestamp: 1706140800,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_naics_code: "325412",
      job_naics_name: "Pharmaceutical Preparation Manufacturing",
    },
    {
      employer_name: "Team2Venture GmbH",
      employer_logo:
        "https://img.advisato.com/assets/images/sites/twago-codice-sconto.jpg?v1470903954",
      employer_website: "http://www.twago.com",
      employer_company_type: null,
      job_publisher: "SmartRecruiters Job Search",
      job_id: "XHZlNdBRPLYAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Frontend Developer (m/w/d)",
      job_apply_link:
        "https://jobs.smartrecruiters.com/Team2VentureGmbH1/743999907558104-frontend-developer-m-w-d-",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.653,
      job_description:
        "Company Description\n\nTwago is a successful, internationally active enterprise on its way to becoming an established online company. The company was acquired by Randstad Holding in 2016, but is operated as a stand-alone entity. We are changing the world of work by connecting freelancers and business clients from all over the world in order to successfully manage various projects.\n\nIn 2017 we launched a white label talent pooling (twago talentpool) solution that allows large companies to build freelancer communities by leveraging their own brand. The great product-market fit gave an enormous impulse to our growth. Today we work with numerous Fortune 500 companies on three different continents.\n\nIn line with the Randstad strategy, we want to combine High Tech with High Touch. Translated to twago we want to add touch experience in the matches of our clients and freelancers. For that, we work with the newest methodologies like growth hacking, agile development and have a strong marketing automation focus.\n\ntwago is a successful, internationally active enterprise on its way to becoming an established online company. We are changing the world of teamwork by connecting freelancers and business clients from all over the world in order to successfully manage various projects. Recently, our new product Twago Enterprise was launched allowing fortune 500 companies to attract freelance talent.\n\nFor our office in the heart of Berlin we are looking for you to start as soon as possible as a Frontend Developer\n\nJob Description\n\nAs part of an experienced, high-performing development team (currently 15 people) you will have a major responsibility for our Frontend Development. You play an essential role in the process of delivering meaningful products and features to our platform and move your team forward. Delivering an excellent user experience across desktop and mobile clients is what drives you.\n\nQualifications\n• You have a BS in Computer Science, Software Engineering, a related academic area or equivalent work experience\n• 4+ years of work experience delivering world-class web applications, proficiency experience with REST APIs, front-end performance optimisation.\n• Expert in markup and styling implementation, using the best of semantic HTML5 and CSS3 * Remarkable JavaScript coding expertise, strong experience with VueJS & NuxtJS\n• Basic understanding of the relevant protocols like Http & WebSockets\n• Excellent written communication and documentation abilities in English\n\nRequirements:\n• VueJS, NuxtJS, Webpack\n• Experience working with Vuetify, Buefy or other VueJS based component library\n• CSS3, HTML5, JavaScript\n• CSS preprocessors like SASS/SCSS\n• Skills in jQuery, RequireJS (might need to support legacy code),\n• Understanding, git and git flow.\n• Some experience in backend development (Java, JSP)\n• Basic understanding of SEO principles\n• Agile/Scrum experience\n• A public portfolio of relevant work that you are proud to share\n\nAdditional Information\n\nWhat's in it for you\n\n• Flexible working time arrangements\n• Option to choose your computer and equipment from an available selection\n• Working alongside an experienced, successful and international team\n• Competitive salary and very attractive office in the heart of Berlin (Kreuzberg)\n• An ideal environment in which you can grow within a start-up atmosphere\n• A fantastic opportunity to learn and do more outside of your current comfort zone\n• Increasing autonomy, authority, and accountability based on your contributions\n• Opportunity to bring in and realize your own ideas\n• Fresh fruits, drinks and joined lunch every week\n• Working on Europe's largest online platform for freelance work\n\nBecome a part of our team!\nPlease send your application as “Front end Developer (m/f/d)” with your availability and salary expectations. We look forward to meeting you!",
      job_is_remote: false,
      job_posted_at_timestamp: 1684223223,
      job_posted_at_datetime_utc: "2023-05-16T07:47:03.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=XHZlNdBRPLYAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 48,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
    },
    {
      employer_name: "EPAM Systems",
      employer_logo:
        "https://upload.wikimedia.org/wikipedia/commons/7/72/Effective_Programming_for_America_logo.svg",
      employer_website: "http://www.epam.com",
      employer_company_type: "Computer Services",
      job_publisher: "关于亿磐",
      job_id: "GaphST93zYkAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Senior Front-End Developer (m/f/d)",
      job_apply_link:
        "https://careers.epam.cn/job-listings/job.90478.senior-front-end-developer-m-f-d_berlin_germany",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.7395,
      job_description:
        "Are you a Senior Frontend Engineer seeking a new challenge? Look no further!\n\nOur development team is seeking a seasoned professional to work on a challenging long-term project with one of our esteemed clients.\nThis project is a crucial part of the client's strategy and involves the optimization of core processes and development of a brand-new core system. Join us and take your skills to the next level!\nes.\n\nWHAT YOU’LL DO\n• Implement functional requirements and technical basic and cross-sectional services\n• Contribution of methodical know-how on architecture and development level for a sustainable, modern target system conception, specifications and methodical control of the development process\n• Establish a developer manuals and documentation\n• Developmental support of test management and implementation of development related test scenarios\n\nWHAT YOU HAVE\n• Knowledge of modern JavaScript frameworks, e.g. Angular, React, Vue\n• Experience in designing user-centered user experience and Operating principles (user experience)\n• Experience in user interface design (UI design)\n• Experience with product-oriented architectures, e.g. REST interfaces, service meshes\n• Experience and understanding of modern agile software development processes according to SAFe\n• Excellent German and English language skills are mandatory\n• You’ll be expected to work on client site 30% of the time\n\nWE OFFER\n• EPAM Employee Stock Purchase Plan (ESPP)\n• 30 days holiday per annum\n• Company Pension Scheme\n• Competitive compensation depending on experience and skills\n• Regular performance assessments\n• Opportunities for personal and professional growth\n• Unlimited access to LinkedIn learning solutions\n• Friendly and enjoyable working team\n• Relocation package support\n• Regular corporate and social events\n• Flexible and remote working opportunities\n• All benefits and perks are subject to specific eligibility requirements\n\nABOUT EPAM\n• EPAM is a leading global provider of digital platform engineering and development services. We are committed to having a positive impact on our customers, our employees, and our communities. We embrace a dynamic and inclusive culture. Here you will collaborate with multi-national teams, contribute to a myriad of innovative projects that deliver the most creative and cutting-edge solutions, and have an opportunity to continuously learn and grow. No matter where you are located, you will join a dedicated, creative, and diverse community that will help you discover your fullest potential\n\nWHY JOIN EPAM\n• Work across markets and verticals and gain exposure to a great variety of projects and cutting-edge technologies\n• Become part of a global community of 60,250 well-connected experts across 50+ countries: enjoy a career without borders within an international environment and relocation opportunities\n• Carve your career path: as the Fastest-Growing IT Services Company in the Fortune 100 List, EPAM is committed to help you discover your fullest potential by creating career plans that best suit you and your future plans\n• EPAM Germany was named a Top Company 2022 & 2023 by Kununu for its people centric culture built on life-long learning",
      job_is_remote: false,
      job_posted_at_timestamp: 1688083200,
      job_posted_at_datetime_utc: "2023-06-30T00:00:00.000Z",
      job_city: "Berlin",
      job_state: "BE",
      job_country: "DE",
      job_latitude: 52.520008,
      job_longitude: 13.404954,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+berlin,+germany&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+berlin,+germany&htidocid=GaphST93zYkAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {},
      job_job_title: "Senior",
      job_posting_language: "en",
      job_onet_soc: "15113400",
      job_onet_job_zone: "3",
      job_naics_code: "541512",
      job_naics_name: "Computer Systems Design Services",
    },
  ],
};
